// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/** Placeholder only used by `prisma generate` in CI, where secrets are absent. */
const CI_DATABASE_URL = "postgresql://ci:ci@127.0.0.1:5432/ci";

if (!process.env.DATABASE_URL?.trim()) {
  process.env.DATABASE_URL = CI_DATABASE_URL;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
