%%{init: {"theme": "base", "themeVariables": {"darkMode": false, "background": "#ffffff", "mainBkg": "#ffffff", "secondaryBkg": "#ffffff", "tertiaryBkg": "#ffffff", "fontFamily": "Arial", "fontSize": "18px", "textColor": "#333333", "lineColor": "#333333", "signalColor": "#333333", "signalTextColor": "#333333"}}}%%
sequenceDiagram
    actor Admin as Administrateur OBC ou DECC
    participant Sys as Systeme DR-DOCSCOL
    participant DB as Base de donnees

    Admin->>Sys: ajouter un ou plusieurs eleves
    Sys-->>Admin: Afficher les formulaires d ajout manuel et d import CSV
    Admin->>Sys: saisir les details(eleve, examen, document optionnel) ou importer un fichier CSV

    alt Donnees valides
        Sys->>DB: enregistrer les profils eleves, examens valides et documents
        DB-->>Sys: confirmer l enregistrement
        Sys-->>Admin: confirmer l ajout des eleves(les rendez-vous seront pris par les eleves)
    else Donnees invalides
        Sys-->>Admin: afficher le message d erreur(donnees manquantes, hors perimetre regional ou fichier CSV invalide)
    end
