ALTER TYPE "StatutRendezVous" ADD VALUE IF NOT EXISTS 'HONORE';
ALTER TYPE "StatutDocument" ADD VALUE IF NOT EXISTS 'PAS_DISPONIBLE';
ALTER TYPE "StatutDocument" ADD VALUE IF NOT EXISTS 'DISPONIBLE';
ALTER TYPE "TypeDocument" ADD VALUE IF NOT EXISTS 'ORIGINAL';
ALTER TYPE "TypeDocument" ADD VALUE IF NOT EXISTS 'RELEVE_NOTES';

DO $$ BEGIN
  CREATE TYPE "DiplomePrincipal" AS ENUM ('BEPC', 'PROBATOIRE', 'BACCALAUREAT');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
